<template>
  <div class="modal">
    <div class="header">
      <span class="close" @click="closeModal">&times;</span>
      <h2 class="heading">
        Item {{ mode === 'edit' ? 'Edit' : mode === 'view' ? 'View' : 'Entry' }} Form
      </h2>
      <div class="modal-content">
        <form @submit.prevent="submitForm" v-if="mode !== 'view'">
          <div class="form-group">
            <label for="item_list">Code:</label>
            <input
              id="item_list"
              v-model="form.item_list"
              type="text"
              required
              readonly
              :placeholder="form.item_list ? '' : 'Code will be generated by the system.'"
            />
            <RiLockFill class="lock-icon" />
          </div>
          <div class="form-group">
            <label for="material_desc">Description:</label>
            <textarea
              id="material_desc"
              v-model="form.description"
              :readonly="mode === 'view'"
              required
            ></textarea>
          </div>
          <div class="form-group">
            <label for="qty">Qty:</label>
            <input id="qty" v-model="form.qty" type="number" value="0" required readonly />
            <RiLockFill class="lock-icon" />
          </div>
          <div class="form-group">
            <label for="unit">Unit:</label>
            <div class="autocomplete">
              <input
                id="unit"
                v-model="searchUnitText"
                type="text"
                @input="handleUnitlistSearch"
                @focus="showUnitList = true"
                @blur="handleUnitlistBlur"
                placeholder="Search or select a Unit"
                required
                :readonly="mode === 'view'"
              />
              <ul v-if="showUnitList && mode !== 'view'" class="category-list">
                <li
                  v-for="unit in filteredUnitlists"
                  :key="unit.unit"
                  @click="selectUnitlist(unit)"
                >
                  {{ unit.unit }}
                </li>
              </ul>
            </div>
          </div>
          <div class="form-group">
            <label for="category">Category:</label>
            <div class="autocomplete">
              <input
                id="category"
                v-model="searchCategoryText"
                type="text"
                @input="handleCategorySearch"
                @focus="showCategoryList = true"
                @blur="handleCategoryBlur"
                placeholder="Search or select a category"
                :readonly="mode === 'edit'"
                required
              />
              <!-- :readonly="mode === 'view'" -->

              <ul v-if="showCategoryList && mode === 'entry'" class="category-list">
                <li
                  v-for="category in filteredCategory"
                  :key="category.description"
                  @click="selectCategory(category)"
                >
                  {{ category.description }}
                </li>
              </ul>
            </div>
            <RiLockFill v-if="mode === 'edit'" class="lock-icon" />
          </div>
          <div class="form-group">
            <label for="supplier_id">Supplier:</label>
            <div class="autocomplete">
              <input
                id="supplier_id"
                v-model="searchSupplierText"
                type="text"
                @input="handleSupplierSearch"
                @focus="showSupplierList = true"
                @blur="handleSupplierBlur"
                placeholder="Search or select a supplier"
                required
                :readonly="mode === 'view'"
              />
              <ul v-if="showSupplierList && mode !== 'view'" class="category-list">
                <li
                  v-for="supplier in filteredSuppliers"
                  :key="supplier.id"
                  @click="selectSupplier(supplier)"
                >
                  {{ supplier.s_name }}
                </li>
              </ul>
            </div>
          </div>
          <div class="button-group">
            <button type="submit" class="btn btn-primary" v-if="mode !== 'view'">
              <RiSave3Fill class="web-icons" />
              {{ inventory ? 'Update' : 'Save' }}
            </button>
            <button type="button" class="btn btn-secondary" @click="closeModal">
              <RiCloseCircleFill class="web-icons" />
              Cancel
            </button>
          </div>
        </form>
        <!-- below code is for view only -->
        <div v-else>
          <div class="form-group">
            <label for="item_list">Code:</label>
            <input id="item_list" v-model="form.item_list" readonly />
          </div>
          <div class="form-group">
            <label for="description">Description:</label>
            <textarea id="description" v-model="form.description" readonly></textarea>
          </div>
          <div class="form-group">
            <label for="qty">Qty:</label>
            <input id="qty" v-model="form.qty" type="number" readonly />
          </div>
          <div class="form-group">
            <label for="unit">Unit:</label>
            <input id="unit" v-model="form.unit" type="text" readonly />
          </div>
          <div class="form-group">
            <label for="category">Category:</label>
            <input id="category" v-model="form.category" type="text" readonly />
          </div>
          <div class="form-group">
            <label for="supplier_id">Supplier:</label>
            <input id="supplier_id" v-model="form.s_name" type="text" readonly />
          </div>
          <div class="button-group">
            <button type="button" class="btn btn-secondary" @click="closeModal">
              <RiCloseCircleFill class="web-icons" />
              Close
            </button>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import axios from 'axios'
import { defineProps, defineEmits } from 'vue'
import { ref, onMounted, computed } from 'vue'
import { useSuppliersStore } from '@/stores/suppliers'
import { useUnitlistsStore } from '@/stores/unitlist'
import { useAuthStore } from '@/stores/auth'
import { useCategoriesStore } from '@/stores/categories'
import useNotification from '@/service/notificationService'
import { RiLockFill, RiCloseCircleFill, RiSave3Fill } from '@remixicon/vue'

const props = defineProps({
  inventory: {
    type: Object,
    default: null
  },
  mode: {
    type: String,
    default: 'entry' // 'entry', 'edit', or 'view'
  }
})

const siteurl = import.meta.env.VITE_API_URL
const { notify } = useNotification()
const suppliersStore = useSuppliersStore()
const categoryStore = useCategoriesStore()
const unitlistStore = useUnitlistsStore()
const authStore = useAuthStore()
const csrfToken = document.querySelector('meta[name="csrf-token"]').getAttribute('content')

const form = ref({
  item_list: props.inventory ? props.inventory.item_list : '',
  description: props.inventory ? props.inventory.description : '',
  qty: props.inventory ? props.inventory.qty : '0',
  unit: props.inventory ? props.inventory.unit : '',
  category: props.inventory ? props.inventory.category : '',
  supplier_id: props.inventory ? props.inventory.supplier_id : '',
  s_name: props.inventory ? props.inventory.s_name : ''
})

const searchCategoryText = ref('')
const showCategoryList = ref(false)

const searchSupplierText = ref('')
const showSupplierList = ref(false)

const searchUnitText = ref('')
const showUnitList = ref(false)

onMounted(async () => {
  await suppliersStore.fetchSuppliers()
  await categoryStore.fetchCategories()
  await unitlistStore.fetchUnitlists()

  if (props.inventory) {
    searchCategoryText.value = props.inventory.category
    searchUnitText.value = props.inventory.unit
    searchSupplierText.value = props.inventory.s_name
  }
})

const handleCategorySearch = () => {
  showCategoryList.value = true
}

const handleCategoryBlur = () => {
  setTimeout(() => {
    showCategoryList.value = false
  }, 200)
}

const selectCategory = (category) => {
  form.value.category = category.description
  searchCategoryText.value = category.description
  showCategoryList.value = false
}

const filteredCategory = computed(() => {
  if (!categoryStore.categories) return []
  const search = searchCategoryText.value.toLowerCase()
  return categoryStore.categories.filter((category) =>
    category.description.toLowerCase().includes(search)
  )
})

const handleSupplierSearch = () => {
  showSupplierList.value = true
}

const handleSupplierBlur = () => {
  setTimeout(() => {
    showSupplierList.value = false
  }, 200)
}

const selectSupplier = (supplier) => {
  form.value.supplier_id = supplier.id
  searchSupplierText.value = supplier.s_name
  showSupplierList.value = false
}

const filteredSuppliers = computed(() => {
  if (!suppliersStore.suppliers) return []
  const search = searchSupplierText.value.toLowerCase()
  return suppliersStore.suppliers.filter((supplier) =>
    supplier.s_name.toLowerCase().includes(search)
  )
})

const handleUnitlistSearch = () => {
  showUnitList.value = true
}

const handleUnitlistBlur = () => {
  setTimeout(() => {
    showUnitList.value = false
  }, 200)
}

const selectUnitlist = (unit) => {
  form.value.unit = unit.unit
  searchUnitText.value = unit.unit
  showUnitList.value = false
}

const filteredUnitlists = computed(() => {
  if (!unitlistStore.unitlists) return []
  const search = searchUnitText.value.toLowerCase()
  return unitlistStore.unitlists.filter((unit) => unit.unit.toLowerCase().includes(search))
})

const emit = defineEmits(['close', 'refresh'])
const closeModal = () => {
  emit('close')
}

const submitForm = async () => {
  try {
    const headers = {
      'Content-Type': 'application/json',
      Accept: 'application/json',
      Authorization: authStore.token,
      'X-CSRF-TOKEN': csrfToken
    }

    let response

    if (props.inventory) {
      response = await axios.put(
        `${siteurl}/api/inventory/update?code=${props.inventory.item_list}`,
        form.value,
        {
          headers
        }
      )
    } else {
      response = await axios.post(`${siteurl}/api/inventory/save`, form.value, { headers })
    }

    if (response.status >= 200 && response.status < 300) {
      notify(response.data.message || 'Purchase saved successfully', 'success')
      emit('refresh')
      emit('close')
    } else {
      notify(response.data.message || 'Failed to save purchase', 'error')
    }
  } catch (error) {
    console.error('Error:', error)
    notify(error.response?.data?.message || 'An error occurred while saving purchase', 'error')
  }
}
</script>

<style lang="scss" scoped>
.modal {
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  background: rgba(0, 0, 0, 0.5);
  display: flex;
  justify-content: center;
  align-items: center;
}

.header {
  font-size: 1.5rem;
  margin: 1rem;
  position: relative;
  background: #007bff;
  padding: 1.5rem 0;
  border-radius: 0.8rem;
  width: 60rem;
  max-width: 90%;
  box-shadow: 0 0.4rem 0.8rem rgba(0, 0, 0, 0.2);

  .heading {
    color: white;
    margin-left: 1.5rem;
  }
}

.modal-content {
  margin-top: 1rem;
  background: white;
  padding: 1.5rem;
  font-size: 1.2rem;
  .lock-icon2 {
    position: relative;
    //transform: translateY(-50%);
    width: 1.5rem;
    height: 1.5rem;
    color: #6c757d;
  }
}

.close {
  position: absolute;
  color: white;
  top: 1rem;
  right: 1rem;
  font-size: 2.4rem;
  cursor: pointer;
}

.form-group {
  display: flex;
  align-items: center;
  gap: 1rem;
  margin-bottom: 0.5rem;

  label {
    width: 10rem;
    font-weight: bold;
  }

  input,
  textarea {
    flex: 1;
    padding: 0.5rem;
    font-size: 1.4rem;
    border: 0.1rem solid #ccc;
    border-radius: 0.4rem;
    background-color: rgb(245, 244, 226);
  }

  .lock-icon {
    position: relative;
    right: 5rem;
    top: 1rem;
    transform: translateY(-50%);
    width: 1.5rem;
    height: 1.5rem;
    color: #6c757d;
  }

  input:focus,
  textarea:focus {
    outline: none;
    border-color: #007bff;
    background-color: #d3f9d8; /* Light green background on focus */
  }

  textarea {
    resize: vertical;
    height: 5rem;
  }
}

.autocomplete {
  position: relative;

  .category-list {
    position: absolute;
    top: 100%;
    left: 0;
    right: 0;
    max-height: 20rem;
    overflow-y: auto;
    background: #f0f0f0;
    border: 0.1rem solid blue;
    border-top: none;
    z-index: 1000;

    li {
      padding: 1rem;
      cursor: pointer;

      &:hover {
        background: #d4d4d4;
      }
    }
  }
}

.button-group {
  display: flex;
  justify-content: flex-end;
  gap: 1rem;

  .btn {
    display: flex;
    align-items: center;
    gap: 0.5rem;
    padding: 1rem 2rem;
    font-size: 1.6rem;
    border: none;
    border-radius: 0.4rem;
    cursor: pointer;
    transition: background-color 0.3s ease;
  }

  .btn-primary {
    background-color: #007bff;
    color: white;

    &:hover {
      background-color: #0056b3;
    }
  }

  .btn-secondary {
    background-color: #6c757d;
    color: white;

    &:hover {
      background-color: #5a6268;
    }
  }

  .web-icons {
    width: 2rem;
    height: 2rem;
  }
}
</style>
