<template>
  <div class="modal">
    <div class="header">
      <span class="close" @click="closeModal">&times;</span>
      <h2 class="heading">
        Item {{ mode === 'edit' ? 'Edit' : mode === 'view' ? 'View' : 'Entry' }} Form
      </h2>
      <div class="modal-content">
        <form @submit.prevent="submitForm" v-if="mode !== 'view'">
          <div class="form-group">
            <label for="id">ID:</label>
            <input
              id="item_list"
              v-model="form.id"
              type="text"
              required
              readonly
              :placeholder="form.item_list ? '' : 'Id will be generated by the system.'"
            />
            <RiLockFill v-if="mode !== 'view'" class="lock-icon" />
          </div>
          <div class="form-group">
            <label for="s_name">Supplier:</label>
            <textarea
              id="s_name"
              v-model="form.s_name"
              type="text"
              :readonly="mode === 'view'"
              required
            ></textarea>
          </div>
          <div class="form-group">
            <label for="mobile1">Mobile (Pri):</label>
            <input
              id="mobile1"
              v-model="form.mobile1"
              type="text"
              required
              :readonly="mode === 'view'"
            />
          </div>
          <div class="form-group">
            <label for="mobile2">Mobile (Sec):</label>
            <input
              id="mobile2"
              v-model="form.mobile2"
              type="text"
              required
              :readonly="mode === 'view'"
            />
          </div>

          <div class="form-group">
            <label for="c_person">Contact Person:</label>
            <input
              id="c_person"
              v-model="form.c_person"
              type="text"
              required
              :readonly="mode === 'view'"
            />
          </div>
          <div class="form-group">
            <label for="contact_info">Contact information:</label>
            <textarea
              id="contact_info"
              v-model="form.contact_info"
              type="text"
              required
              :readonly="mode === 'view'"
            />
          </div>
          <div class="button-group">
            <button type="submit" class="btn btn-primary" v-if="mode !== 'view'">
              <RiSave3Fill class="web-icons" />
              {{ supplier ? 'Update' : 'Save' }}
            </button>
            <button type="button" class="btn btn-secondary" @click="closeModal">
              <RiCloseCircleFill class="web-icons" />
              Cancel
            </button>
          </div>
        </form>
        <!-- below code is for view only -->
        <div v-else>
          <div class="form-group">
            <label for="id">ID:</label>
            <input id="id" v-model="form.id" type="text" readonly />
          </div>
          <div class="form-group">
            <label for="s_name">Supplier:</label>
            <input id="s_name" v-model="form.s_name" type="text" readonly />
          </div>
          <div class="form-group">
            <label for="mobile1">Mobile (Pri):</label>
            <input id="mobile1" v-model="form.mobile1" type="text" readonly />
          </div>
          <div class="form-group">
            <label for="mobile2">Mobile (Sec):</label>
            <input id="mobile2" v-model="form.mobile2" type="text" readonly />
          </div>
          <div class="form-group">
            <label for="c_person">Contact Person:</label>
            <input id="c_person" v-model="form.c_person" type="text" readonly />
          </div>
          <div class="form-group">
            <label for="contact_info">Contact information:</label>
            <textarea id="contact_info" v-model="form.contact_info" type="text" readonly />
          </div>
          <div class="button-group">
            <button type="button" class="btn btn-secondary" @click="closeModal">
              <RiCloseCircleFill class="web-icons" />
              Close
            </button>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import axios from 'axios'
import { defineProps, defineEmits } from 'vue'
import { ref } from 'vue'
//import { useSuppliersStore } from '@/stores/suppliers'
//import { useUnitlistsStore } from '@/stores/unitlist'
import { useAuthStore } from '@/stores/auth'
//import { useCategoriesStore } from '@/stores/categories'
import useNotification from '@/service/notificationService'
import { RiLockFill, RiCloseCircleFill, RiSave3Fill } from '@remixicon/vue'

const props = defineProps({
  supplier: {
    type: Object,
    default: null
  },
  mode: {
    type: String,
    default: 'entry' // 'entry', 'edit', or 'view'
  }
})

const siteurl = import.meta.env.VITE_API_URL
const { notify } = useNotification()
//const suppliersStore = useSuppliersStore()
//const categoryStore = useCategoriesStore()
//const unitlistStore = useUnitlistsStore()
const authStore = useAuthStore()
const csrfToken = document.querySelector('meta[name="csrf-token"]').getAttribute('content')

const form = ref({
  id: props.supplier ? props.supplier.id : '',
  s_name: props.supplier ? props.supplier.s_name : '',
  mobile1: props.supplier ? props.supplier.mobile1 : '',
  mobile2: props.supplier ? props.supplier.mobile2 : '',
  c_person: props.supplier ? props.supplier.c_person : '',
  contact_info: props.supplier ? props.supplier.contact_info : ''
})

const emit = defineEmits(['close', 'refresh'])
const closeModal = () => {
  emit('close')
}

const submitForm = async () => {
  try {
    const headers = {
      'Content-Type': 'application/json',
      Accept: 'application/json',
      Authorization: authStore.token,
      'X-CSRF-TOKEN': csrfToken
    }

    let response

    if (props.supplier) {
      response = await axios.put(
        `${siteurl}/api/suppliers/update?id=${props.supplier.id}`,
        form.value,
        {
          headers
        }
      )
    } else {
      response = await axios.post(`${siteurl}/api/suppliers/save`, form.value, { headers })
    }

    if (response.status >= 200 && response.status < 300) {
      notify(response.data.message || 'Supplier saved successfully', 'success')
      emit('refresh')
      emit('close')
    } else {
      notify(response.data.message || 'Failed to save Supplier', 'error')
    }
  } catch (error) {
    if (error.response) {
      // Handle specific status codes
      if (error.response.status >= 400 && error.response.status < 500) {
        // Notify user with the error message
        notify(error.response.data.error, 'error')
      } else if (error.response.status >= 500) {
        // Handle server errors
        notify('Server error occurred. Please try again later.', 'error')
      }
    } else {
      // Handle network errors or no response from server
      notify(
        'Network or server error occurred. Please check your connection and try again.',
        'error'
      )
    }
  }
}
</script>

<style lang="scss" scoped>
.modal {
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  background: rgba(0, 0, 0, 0.5);
  display: flex;
  justify-content: center;
  align-items: center;
}

.header {
  font-size: 1.5rem;
  margin: 1rem;
  position: relative;
  background: #007bff;
  padding: 1.5rem 0;
  border-radius: 0.8rem;
  width: 60rem;
  max-width: 90%;
  box-shadow: 0 0.4rem 0.8rem rgba(0, 0, 0, 0.2);

  .heading {
    color: white;
    margin-left: 1.5rem;
  }
}

.modal-content {
  margin-top: 1rem;
  background: white;
  padding: 1.5rem;
  font-size: 1.2rem;
  .lock-icon2 {
    position: relative;
    //transform: translateY(-50%);
    width: 1.5rem;
    height: 1.5rem;
    color: #6c757d;
  }
}

.close {
  position: absolute;
  color: white;
  top: 1rem;
  right: 1rem;
  font-size: 2.4rem;
  cursor: pointer;
}

.form-group {
  display: flex;
  align-items: center;
  gap: 1rem;
  margin-bottom: 0.5rem;

  label {
    width: 10rem;
    font-weight: bold;
  }

  input,
  textarea {
    flex: 1;
    padding: 0.5rem;
    font-size: 1.4rem;
    border: 0.1rem solid #ccc;
    border-radius: 0.4rem;
    background-color: rgb(245, 244, 226);
  }

  .lock-icon {
    position: relative;
    right: 5rem;
    top: 1rem;
    transform: translateY(-50%);
    width: 1.5rem;
    height: 1.5rem;
    color: #6c757d;
  }

  input:focus,
  textarea:focus {
    outline: none;
    border-color: #007bff;
    background-color: #d3f9d8; /* Light green background on focus */
  }

  textarea {
    resize: vertical;
    height: 5rem;
  }
}

.autocomplete {
  position: relative;

  .category-list {
    position: absolute;
    top: 100%;
    left: 0;
    right: 0;
    max-height: 20rem;
    overflow-y: auto;
    background: #f0f0f0;
    border: 0.1rem solid blue;
    border-top: none;
    z-index: 1000;

    li {
      padding: 1rem;
      cursor: pointer;

      &:hover {
        background: #d4d4d4;
      }
    }
  }
}

.button-group {
  display: flex;
  justify-content: flex-end;
  gap: 1rem;

  .btn {
    display: flex;
    align-items: center;
    gap: 0.5rem;
    padding: 1rem 2rem;
    font-size: 1.6rem;
    border: none;
    border-radius: 0.4rem;
    cursor: pointer;
    transition: background-color 0.3s ease;
  }

  .btn-primary {
    background-color: #007bff;
    color: white;

    &:hover {
      background-color: #0056b3;
    }
  }

  .btn-secondary {
    background-color: #6c757d;
    color: white;

    &:hover {
      background-color: #5a6268;
    }
  }

  .web-icons {
    width: 2rem;
    height: 2rem;
  }
}
</style>
